package domain

import "time"

// EditalAnalysisStatus defines the state of the analysis.
type EditalAnalysisStatus string

const (
	EditalStatusProcessando EditalAnalysisStatus = "PROCESSANDO"
	EditalStatusConcluido   EditalAnalysisStatus = "CONCLUIDO"
	EditalStatusErro        EditalAnalysisStatus = "ERRO"
)

// SeveridadeRisco defines the risk level of clauses.
type SeveridadeRisco string

const (
	SeveridadeCritica SeveridadeRisco = "CRITICA" // Alto risco de desclassificação imediata ou prejuízo financeiro
	SeveridadeAtencao SeveridadeRisco = "ATENCAO" // Exige cuidado e comprovação específica
	SeveridadeNormal  SeveridadeRisco = "NORMAL"  // Procedimento padrão de licitação
)

// EditalAnalysis represents the full structured intelligence generated by the Edital AI Analyst.
type EditalAnalysis struct {
	ID                 string               `json:"id"`
	OportunidadeID     *string              `json:"oportunidadeId,omitempty"`
	Titulo             string               `json:"titulo"`
	Orgao              string               `json:"orgao"`
	NumeroEdital       string               `json:"numeroEdital"`
	NumeroProcesso     string               `json:"numeroProcesso"`
	Modalidade         string               `json:"modalidade"`
	ModoDisputa        string               `json:"modoDisputa"`
	ObjetoCompleto     string               `json:"objetoCompleto"`
	Localidade         string               `json:"localidade"`
	DataAbertura       string               `json:"dataAbertura"`
	ValorEstimado      float64              `json:"valorEstimado"`
	BDIMaximoPermitido *float64             `json:"bdiMaximoPermitido,omitempty"`
	PrazoExecucao      string               `json:"prazoExecucao"`
	RegimeExecucao     string               `json:"regimeExecucao"` // ex: "Empreitada por Preço Unitário"
	Status             EditalAnalysisStatus `json:"status"`
	OriginalFileName   string               `json:"originalFileName"`
	FileType           string               `json:"fileType"`
	TotalPaginas       int                  `json:"totalPaginas"`
	ResumoExecutivo    string               `json:"resumoExecutivo"`
	ParecerTecnico     string               `json:"parecerTecnico"`
	ScoreAderencia     float64              `json:"scoreAderencia"` // 0.0 a 10.0
	ErroMensagem       string               `json:"erroMensagem,omitempty"`
	CreatedAt          time.Time            `json:"createdAt"`
	UpdatedAt          time.Time            `json:"updatedAt"`

	// Relational details
	Pegadinhas             []EditalPegadinha            `json:"pegadinhas,omitempty"`
	QualificacoesTecnicas  []EditalQualificacaoTecnica  `json:"qualificacoesTecnicas,omitempty"`
	RequisitosHabilitacao  []EditalRequisitoHabilitacao `json:"requisitosHabilitacao,omitempty"`
	ChecklistDocumentos    []EditalChecklistItem        `json:"checklistDocumentos,omitempty"`
	IndicesFinanceiros     []EditalIndiceFinanceiro     `json:"indicesFinanceiros,omitempty"`
}

// EditalPegadinha represents traps, dangerous clauses, or subtle disqualification criteria.
type EditalPegadinha struct {
	ID          string          `json:"id"`
	AnalysisID  string          `json:"analysisId"`
	Clausula    string          `json:"clausula"` // ex: "Item 7.4.2"
	Titulo      string          `json:"titulo"`
	Descricao   string          `json:"descricao"`
	Severidade  SeveridadeRisco `json:"severidade"` // "CRITICA", "ATENCAO", "NORMAL"
	Recomendacao string         `json:"recomendacao"`
	Impacto     string          `json:"impacto"` // "DESCLASSIFICACAO", "FINANCEIRO", "OPERACIONAL"
}

// EditalQualificacaoTecnica represents minimum technical parcel requirements and capacity certifications.
type EditalQualificacaoTecnica struct {
	ID                 string  `json:"id"`
	AnalysisID         string  `json:"analysisId"`
	ItemServico        string  `json:"itemServico"` // ex: "Pavimentação asfáltica em CBUQ"
	Unidade            string  `json:"unidade"`     // "M2", "M3", "KM"
	QuantidadeExigida  float64 `json:"quantidadeExigida"`
	ParcelaMinima      string  `json:"parcelaMinima"` // ex: "50% do quantitativo da planilha (mín. 15.000 m²)"
	ExigeVisitaTecnica bool    `json:"exigeVisitaTecnica"`
	AceitaDeclaracao   bool    `json:"aceitaDeclaracao"`
	Observacao         string  `json:"observacao,omitempty"`
}

// EditalRequisitoHabilitacao defines standard legal, fiscal, and social requirements.
type EditalRequisitoHabilitacao struct {
	ID         string `json:"id"`
	AnalysisID string `json:"analysisId"`
	Categoria  string `json:"categoria"` // "JURIDICA", "FISCAL_TRABALHISTA", "ECONOMICA", "TECNICA"
	Documento  string `json:"documento"`
	Obrigatorio bool   `json:"obrigatorio"`
	Detalhes   string `json:"detalhes,omitempty"`
}

// EditalChecklistItem represents a checkable proposal submission document.
type EditalChecklistItem struct {
	ID         string `json:"id"`
	AnalysisID string `json:"analysisId"`
	Numero     int    `json:"numero"`
	Descricao  string `json:"descricao"`
	Fase       string `json:"fase"` // "PROPOSTA", "HABILITACAO", "CONTRATACAO"
	Marcado    bool   `json:"marcado"`
	Observacao string `json:"observacao,omitempty"`
}

// EditalIndiceFinanceiro represents required balance sheet indices.
type EditalIndiceFinanceiro struct {
	ID          string  `json:"id"`
	AnalysisID  string  `json:"analysisId"`
	Sigla       string  `json:"sigla"`       // "LG", "LC", "SG", "PL"
	Nome        string  `json:"nome"`        // "Liquidez Geral", "Liquidez Corrente", "Solvência Geral", "Patrimônio Líquido"
	ValorMinimo string  `json:"valorMinimo"` // ">= 1.00", ">= 10% do valor estimado"
	Formula     string  `json:"formula,omitempty"`
	Observacao  string  `json:"observacao,omitempty"`
}
